### ISSUE TITLE
Retrieve NM results files

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nm#1]
New Mexico has an [election results site](http://electionresults.sos.state.nm.us/) that has race-specific Excel files at the county and precinct-level. Beginning with [federal offices](http://electionresults.sos.state.nm.us/resultsSW.aspx?eid=2&type=FED&map=CTY), write a script that scrapes the page and loads each link for "County Results" and then saves the files from the "Export County Level" and "Export Precinct Level" buttons on each county results page. Continue with pages for [statewide offices](http://electionresults.sos.state.nm.us/resultsSW.aspx?eid=2&type=SW&map=CTY) and [state legislative offices](http://electionresults.sos.state.nm.us/resultsSW.aspx?eid=2&type=LGX&map=CTY&lValue=100&gValue=001). (You'll probably want to loop through those 3 since the only change to the URL is the `type`. Ideally, this script would be modular enough to accept an `eid` of 1, which is the 2014 primary.)

The county level and precinct-level files should be named `20141104__nm__general__{office}__{county}.xlsx` and `20141104__nm__general__{office}__{county}__precinct.xlsx`, where office is one of `senate`, `house__{district}`,  `governor`, `secretary_of_state`, `state_auditor`, `state_treasurer`, `attorney_general`, `commissioner_of_public_lands`, `state_house__{district}`.

You can use a dictionary to map office names to their slug versions for the file names, and remember to grab the district for U.S. House and State House races.

**Comment by gordonje** [comment]
On it!
