### ISSUE TITLE
Create combined CSV files for 2016 primary and general elections

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nm#12]
For both the 2016 [general](https://github.com/openelections/openelections-data-nm/tree/master/2016/general) and [primary](https://github.com/openelections/openelections-data-nm/tree/master/2016/primary), take the Excel files and generate a single CSV for each election (can you one for each party's primary if that's easier).

The names of the CSV files should have the following format: `yymmdd__nm__general__precinct.csv` for general election and `yymmdd__nm__primary__precinct.csv`

We're interested in results for all federal and state offices, but if you want to generate files for the entire file, that's fine.

And the CSV files should have at least these fields: `county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

Include a precinct total for each candidate.

- [x] 2016 general
- [x] 2016 primary

**Comment by greencracker** [comment]
So the final file would look like:
county, precinct, office, district, party, candidate, votes
Bernalillo, PCT 001, president, NA, Republican, Donald Trump, 311
Bernalillo, PCT 001, president, NA, Democrat, Hillary Clinton, 346
... etc all the presidential candidates in every precinct and county
Bernalillo, PCT 001, secretary of state, NA, Republican, Nora Espinoza, 299
.. etc for all the statewide offices

**Comment by dwillis** [comment]
Yes, basically. Titlecase for office names and you can just leave the district empty for statewide offices.
