### ISSUE TITLE
HTML scraper for 2000-2002 county-level results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nm#3]
http://www.sos.state.nm.us/Elections_Data/2000.aspx
http://www.sos.state.nm.us/Elections_Data/2002.aspx

Each year has general and primary election results, so the resulting CSV files should all have the following headers:

`county`, `office`, `district`, `party`, `candidate`, `votes`

and the files should be named:

`20021105__nm__general__county.csv` (2002 general)
`20020604__nm__primary__county.csv` (2002 primary)
`20001107__nm__general__county.csv` (2000 general)
`20000606__nm__primary__county.csv` (2000 primary)

In terms of offices, use the name in the HTML files, and we're interested in federal, statewide and state legislative races. For districts, try to capture the number only.

**Comment by cmcenaney** [comment]
Working on this
